---
kind: pipeline
type: kubernetes
name: terraform

trigger:
  event:
    include:
      - pull_request

steps:
  - name: tf-plan
    image: hashicorp/terraform:light
    environment:
      GITHUB_PRIVATE_KEY:
        from_secret: GITHUB_PRIVATE_KEY
    volumes:
      - name: tmpfs
        path: /tmpfs
    commands:
      terraform init
